sudo: required
services:
  - docker

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qttools5-dev-tools
  - qmake -version

script:
  - qmake -project
  - qmake s3inlc/holm/src/holm-alpha/holm-alpha.pro
  - make